### PR TITLE
Add solver options

### PR DESCRIPTION
**Pull request by blegat**

### CODE REVIEW

**Comment by blegat** [comment]
I don't know what is happening on Travis. The build log just says "An error occurred while generating the build script."
@joehuchette Could you restart it ?

**Comment by joehuchette** [comment]
Restarted

**Comment by blegat** [comment]
Thanks ! Linux is passing but Mac OS has been killed because "No output has been received in the last 10m0"

**Comment by joehuchette** [comment]
Let me restart again, see if that fixes the issue

**Comment by blegat** [comment]
MacOS build have failed because of https://github.com/JuliaOpt/MathOptInterface.jl/pull/157 which has now been reverted so it should pass now

**Comment by blegat** [comment]
Passing now \o/

**Pull request merged**
